/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.HClubManageRole;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ModelNew.Book;
import ModelNew.Cust;
import ModelNew.CustDirectory;
import ModelNew.HClub;
import ModelNew.Org;
import ModelNew.PhyOrg;
import ModelNew.systAdmin;
import ModelNew.TherapyOrg;
import ModelNew.TrainerOrg;
import ModelNew.services.HClubService;
import ModelNew.services.Service;

/**
 *
 * @author Samikshan
 */
public class ViewTask extends javax.swing.JPanel {
    private systAdmin systAdmin;
    private Runnable callOnCreateMethod;
    private String user;
    private String type;
    private HClub HClub;

    public ViewTask(systAdmin systAdmin, Runnable callOnCreateMethod, String user, String type, HClub HClub) {
        initComponents();
        this.systAdmin = systAdmin;
        this.callOnCreateMethod = callOnCreateMethod;
        this.user = user;
        this.type = type;
        this.HClub = HClub;
        populateComboBox();
        populateTable();
        setBackground(new java.awt.Color(255, 204, 204));
        backButton.setBackground(new java.awt.Color(244, 120, 140));
        backButton.setOpaque(true);
        assignWork.setBackground(new java.awt.Color(244, 120, 140));
        assignWork.setOpaque(true);

    }

    /**
     * Creates new form ViewTask
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        physicianOrg = new javax.swing.JComboBox<>();
        therapistOrg = new javax.swing.JComboBox<>();
        trainerOrg = new javax.swing.JComboBox<>();
        assignWork = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        physicianOrg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        therapistOrg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        trainerOrg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        assignWork.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        assignWork.setText("ASSIGN AND CONFIRM TASK");
        assignWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignWorkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("VIEW ORDER DETAILS");

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDER ID", "NAME", "STATUS", "THERAPIST", "PHYSICIAN", "TRAINER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("SELECT A THERAPIST ORG");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("SELECT A TRAINER ORG");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("SELECT A PHYSICIAN ORG");

        backButton.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backButton)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(299, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(therapistOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(physicianOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(trainerOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(assignWork)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(backButton)
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(therapistOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(physicianOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trainerOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(assignWork, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignWorkActionPerformed
        int selectedRowIndex = jTable1.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Book to assign tasks.");
            return;
        }

        DefaultTableModel Model = (DefaultTableModel) jTable1.getModel();
        Book Book = (Book) Model.getValueAt(selectedRowIndex, 0);

        HClubService HClubService = null;
        for (Service service : Book.getServices()) {
            if (HClub.getName().equals(service.getEnterprise().getName())) {
                HClubService = (HClubService) service;
                break;
            }
        }

        if (HClubService == null) {
            JOptionPane.showMessageDialog(this, "Cannot find health club");
            return;
        }
        if (!HClubService.getStatus().equals(Service.Status.PENDING)) {
            JOptionPane.showMessageDialog(this, String.format("Book '%s' should be 'PENDING' state to be accepted.",
                Book.getId()));
        return;
        }

        TherapyOrg Therapy = (TherapyOrg) TherapyOrg.getSelectedItem();
        PhyOrg Phy = (PhyOrg) PhyOrg.getSelectedItem();
        TrainerOrg trainer = (TrainerOrg) trainerOrg.getSelectedItem();

        List<Org> Orgs = new ArrayList<>();
        for (HClubService.HClubServiceType type : HClubService.getHClubServices()) {
            switch (type) {
                case Therapy:
                if (Therapy == null) {
                    JOptionPane.showMessageDialog(this, "Please select Therapy Org to be assinged for the Book.");
                    return;
                } else {
                    Orgs.add(Therapy);
                }
                break;
                case Phy:
                if (Phy == null) {
                    JOptionPane.showMessageDialog(this, "Please select Phy Org to be assinged for the Book.");
                    return;
                } else {
                    Orgs.add(Phy);
                }
                break;
                case TRAINER:
                if (trainer == null) {
                    JOptionPane.showMessageDialog(this, "Please select trainer Org to be assinged for the Book.");
                    return;
                } else {
                    Orgs.add(trainer);
                }
                break;
            }
        }

        for (Org Org : Orgs) {
            HClubService.addOrg(Org);
        }
        HClubService.setStatus(Service.Status.CONFIRMED);
        JOptionPane.showMessageDialog(this, "Assigned all HClub services to the Book: " + Book.getId());

        return;
    }//GEN-LAST:event_assignWorkActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        callOnCreateMethod.run();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignWork;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<PhysicianOrg> physicianOrg;
    private javax.swing.JComboBox<TherapistOrg> therapistOrg;
    private javax.swing.JComboBox<TrainerOrg> trainerOrg;
    // End of variables declaration//GEN-END:variables


    private void populateTable() {

        DefaultTableModel Model = (DefaultTableModel) jTable1.getModel();
        Model.setRowCount(0);

        Object row[] = new Object[10];
        CustDirectory CustDirec = systAdmin.getCustDirec(); //get all Custs
        for (Cust Cust : CustDirec.getListOfCust()) {
            for (Book Book : Cust.getBkList()) {      //get Book dtls each Cust
                for (Service service : Book.getServices()) {       //get services under Book

                    if (service.getEnterprise().getName().equals(HClub.getName())) {

                        HClubService HClubService = (HClubService) service;

                        row[0] = Book;
                        row[1] = Cust;
                        row[2] = HClubService.getStatus();
                        row[3] = "NO";
                        row[4] = "NO";
                        row[5] = "NO";

                        for (HClubService.HClubServiceType type : HClubService.getHClubServices()) {
                            switch (type) {
                                case Therapy:
                                    row[3] = "YES";
                                    break;
                                case Phy:
                                    row[4] = "YES";
                                    break;
                                case TRAINER:
                                    row[5] = "YES";
                                    break;
                            }
                        }
                        Model.addRow(row);
                    }
                    
                }
            }
        }

    }

    private void populateComboBox() {
        TherapyOrg.addItem(null);
        PhyOrg.addItem(null);
        trainerOrg.addItem(null);

        for (TherapyOrg Therapy : HClub.getListOfTherapyOrg()) {
            if (Therapy != null) {
                TherapyOrg.addItem(Therapy);
            }
        }
        for (PhyOrg Phy : HClub.getListOfPhyOrg()) {
            if (Phy != null) {
                PhyOrg.addItem(Phy);
            }
        }
        for (TrainerOrg trainer : HClub.getListOfTrainerOrg()) {
            if (trainer != null) {
                trainerOrg.addItem(trainer);
            }
        }
    }

}


